import { Lead, SearchCampaign, NicheSummary, DashboardStats } from "./types";

export const mockLeads: Lead[] = [
  {
    id: "1",
    campaignId: "c1",
    name: "Clínica Bella Estética",
    niche: "Clínicas de Estética",
    subniche: "Estética Facial",
    website: "https://bellastetica.com.br",
    instagram: "@bellastetica",
    linkedin: undefined,
    email: "contato@bellastetica.com.br",
    phone: "(11) 98765-4321",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    responsible: "Dra. Fernanda Lima",
    source: "Instagram",
    sourceUrl: "https://instagram.com/bellastetica",
    score: 87,
    temperature: "hot",
    scoreReason: "Está anunciando ativamente (+20), tem página de vendas (+15), usa termos de intenção como 'inscrições abertas' e 'agenda aberta' (+35), mas site tem CTA pouco visível (+10) e funil incompleto (+15).",
    opportunity: "A clínica está captando clientes via Instagram Ads, mas a landing page tem baixa conversão. Há espaço para melhorar o funil de agendamento, qualificação via WhatsApp e remarketing para quem visitou sem converter.",
    suggestedMessage: "Oi, Fernanda! Vi que a Bella Estética está com campanhas rodando no Instagram — parabéns pela iniciativa. Notei que a página de agendamento tem algumas oportunidades de melhoria que podem aumentar bastante a taxa de conversão. Faz sentido eu te mostrar rapidamente o que encontrei?",
    status: "new",
    termsFound: ["agenda aberta", "inscrições abertas", "harmonização facial"],
    problemsFound: ["CTA pouco visível na landing page", "WhatsApp sem qualificação", "Funil incompleto"],
    signals: [
      { id: "s1", leadId: "1", signalType: "advertising", signalDescription: "Anúncios ativos no Meta Ads", points: 20, sourceUrl: "https://facebook.com/ads/library", createdAt: "2026-05-05" },
      { id: "s2", leadId: "1", signalType: "sales_page", signalDescription: "Página de vendas identificada", points: 15, createdAt: "2026-05-05" },
      { id: "s3", leadId: "1", signalType: "intent_terms", signalDescription: "Usa 'agenda aberta' e 'inscrições abertas'", points: 35, createdAt: "2026-05-05" },
    ],
    observations: "",
    createdAt: "2026-05-05T10:30:00Z",
    updatedAt: "2026-05-05T10:30:00Z",
  },
  {
    id: "2",
    campaignId: "c1",
    name: "Prof. Ricardo Mendes — Mentor de Negócios",
    niche: "Infoprodutores",
    subniche: "Mentoria de Negócios",
    website: "https://ricardomendes.com",
    instagram: "@ricardomendesoficial",
    linkedin: "linkedin.com/in/ricardomendes",
    email: "contato@ricardomendes.com",
    phone: "(21) 99887-6543",
    city: "Rio de Janeiro",
    state: "RJ",
    country: "Brasil",
    responsible: "Ricardo Mendes",
    source: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/ricardomendes",
    score: 92,
    temperature: "hot",
    scoreReason: "Lançamento ativo identificado (+20), anunciando no Meta (+20), tem checkout ativo (+15), página de vendas (+15), usa 'lista de espera' e 'mentoria' (+20). Site bem estruturado, mas sem remarketing configurado.",
    opportunity: "Expert em fase de lançamento com alto engajamento. Não possui estrutura de remarketing nem e-mail marketing automatizado. Alta probabilidade de conversão para gestão de tráfego e automação de funil.",
    suggestedMessage: "Oi, Ricardo! Acompanhei seu lançamento e vi que o engajamento está excelente. Identifiquei que há uma oportunidade grande de capturar quem visitou sua página mas não converteu ainda — com remarketing estruturado, você poderia recuperar entre 15% e 30% desses leads. Vale uma conversa rápida?",
    status: "contacted",
    termsFound: ["lançamento", "lista de espera", "mentoria", "vagas limitadas"],
    problemsFound: ["Sem remarketing", "E-mail marketing básico", "Sem automação pós-captura"],
    signals: [
      { id: "s4", leadId: "2", signalType: "launch", signalDescription: "Lançamento ativo com 'lista de espera'", points: 20, createdAt: "2026-05-04" },
      { id: "s5", leadId: "2", signalType: "advertising", signalDescription: "Meta Ads ativo", points: 20, createdAt: "2026-05-04" },
      { id: "s6", leadId: "2", signalType: "checkout", signalDescription: "Checkout Hotmart ativo", points: 15, createdAt: "2026-05-04" },
    ],
    observations: "Cliente respondeu mensagem inicial com interesse. Agendar demo.",
    createdAt: "2026-05-04T14:20:00Z",
    updatedAt: "2026-05-05T09:15:00Z",
  },
  {
    id: "3",
    campaignId: "c2",
    name: "FitLife Academia",
    niche: "Academias",
    subniche: "Musculação e Crossfit",
    website: "https://fitlifeacademia.com.br",
    instagram: "@fitlifeac",
    linkedin: undefined,
    email: "comercial@fitlifeacademia.com.br",
    phone: "(31) 3456-7890",
    city: "Belo Horizonte",
    state: "MG",
    country: "Brasil",
    responsible: "Marcos Oliveira",
    source: "Google Maps",
    sourceUrl: "https://maps.google.com/?cid=fitlife",
    score: 61,
    temperature: "warm",
    scoreReason: "Tem site (+5), Instagram ativo (+5), e-mail público (+5), WhatsApp (+5). Sem anúncios identificados, mas contratando 'personal trainer e coordenador de marketing' (+25). Site com design desatualizado (+10) e formulário confuso (+10).",
    opportunity: "Academia em expansão buscando coordenador de marketing — sinal claro de investimento em crescimento. Momento ideal para oferecer gestão de tráfego e estruturação de captação digital.",
    suggestedMessage: "Oi, Marcos! Vi que a FitLife está crescendo e buscando reforçar o time de marketing — isso é um ótimo sinal. Percebi que há uma oportunidade de acelerar a captação de novos alunos enquanto o time interno se estrutura. Posso te mostrar como outras academias em BH estão captando 40+ alunos por mês com tráfego pago?",
    status: "new",
    termsFound: ["contratando", "coordenador de marketing", "nova unidade"],
    problemsFound: ["Site com design desatualizado", "Formulário confuso", "Sem captação digital estruturada"],
    signals: [
      { id: "s7", leadId: "3", signalType: "hiring", signalDescription: "Contratando coordenador de marketing", points: 25, createdAt: "2026-05-03" },
    ],
    observations: "",
    createdAt: "2026-05-03T11:00:00Z",
    updatedAt: "2026-05-03T11:00:00Z",
  },
  {
    id: "4",
    campaignId: "c2",
    name: "Dr. Paulo Saúde — Consultório Odontológico",
    niche: "Consultórios",
    subniche: "Odontologia Estética",
    website: "https://drpaulosaudeodonto.com.br",
    instagram: "@drpaulosaude",
    linkedin: undefined,
    email: "recepcao@drpaulosaude.com.br",
    phone: "(11) 3344-5566",
    city: "Campinas",
    state: "SP",
    country: "Brasil",
    responsible: "Dr. Paulo Saúde",
    source: "Google Business",
    sourceUrl: "https://g.page/drpaulosaude",
    score: 75,
    temperature: "hot",
    scoreReason: "Anunciando no Google (+20), tem formulário de agendamento (+10), página de vendas (+15). Problema: anuncia mas landing page fraca (+25). Site lento identificado (+10).",
    opportunity: "Dentista investindo em Google Ads mas sem landing page otimizada para converter. Cada clique perdido representa custo sem retorno. Oportunidade direta para CRO e gestão de tráfego.",
    suggestedMessage: "Oi, Dr. Paulo! Vi que vocês estão investindo em Google Ads — ótima estratégia para odontologia estética. Só que identifiquei que a página de destino dos anúncios está perdendo boa parte das conversões. Isso significa que você está pagando por cliques que não viram pacientes. Posso te mostrar exatamente onde está o problema?",
    status: "qualified",
    termsFound: ["agendamento online", "clareamento dental", "harmonização"],
    problemsFound: ["Landing page fraca para os anúncios", "Site lento (3.2s)", "Sem pixel de conversão"],
    signals: [
      { id: "s8", leadId: "4", signalType: "advertising", signalDescription: "Google Ads ativo", points: 20, createdAt: "2026-05-02" },
      { id: "s9", leadId: "4", signalType: "weak_landing", signalDescription: "Anuncia mas landing page fraca", points: 25, createdAt: "2026-05-02" },
    ],
    observations: "Lead qualificado. Enviada proposta de auditoria gratuita.",
    createdAt: "2026-05-02T16:45:00Z",
    updatedAt: "2026-05-05T08:30:00Z",
  },
  {
    id: "5",
    campaignId: "c3",
    name: "Casa & Conforto Imóveis",
    niche: "Imobiliárias",
    subniche: "Imóveis Residenciais",
    website: "https://casaconfortoimoveis.com.br",
    instagram: "@casaconfortoimoveis",
    linkedin: "linkedin.com/company/casaconforto",
    email: "vendas@casaconfortoimoveis.com.br",
    phone: "(48) 99654-3210",
    city: "Florianópolis",
    state: "SC",
    country: "Brasil",
    responsible: "Ana Beatriz Santos",
    source: "LinkedIn",
    sourceUrl: "https://linkedin.com/company/casaconforto",
    score: 54,
    temperature: "warm",
    scoreReason: "Tem site (+5), Instagram (+5), e-mail (+5), WhatsApp (+5). Contratando corretor e social media (+25). Site sem CTA claro (+10). Sem anúncios ativos identificados.",
    opportunity: "Imobiliária em fase de expansão da equipe digital. Captação ainda é feita de forma orgânica. Oportunidade para estruturar captação via tráfego pago para lançamentos imobiliários.",
    suggestedMessage: "Oi, Ana! Vi que a Casa & Conforto está expandindo o time e buscando social media — ótimo momento para também estruturar a captação digital de compradores. Como vocês estão captando leads qualificados hoje? Tenho um modelo que tem funcionado bem para imobiliárias em SC.",
    status: "new",
    termsFound: ["contratando corretor", "novos empreendimentos", "financiamento facilitado"],
    problemsFound: ["Sem anúncios estruturados", "CTA pouco claro no site", "Captação apenas orgânica"],
    signals: [
      { id: "s10", leadId: "5", signalType: "hiring", signalDescription: "Contratando social media e corretor", points: 25, createdAt: "2026-05-01" },
    ],
    observations: "",
    createdAt: "2026-05-01T09:00:00Z",
    updatedAt: "2026-05-01T09:00:00Z",
  },
  {
    id: "6",
    campaignId: "c1",
    name: "Sabor & Arte Restaurante",
    niche: "Restaurantes",
    subniche: "Culinária Italiana",
    website: undefined,
    instagram: "@saborarterestaurante",
    linkedin: undefined,
    email: undefined,
    phone: "(11) 3789-0123",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    responsible: "Chef Marco Rossi",
    source: "Google Maps",
    sourceUrl: "https://maps.google.com/?cid=saborarte",
    score: 28,
    temperature: "cold",
    scoreReason: "Tem Instagram (+5), WhatsApp (+5). Sem site (+0), sem e-mail comercial (+0). Pouca presença digital. Sem sinais de intenção identificados. Instagram com baixo engajamento.",
    opportunity: "Restaurante com boa avaliação no Google (4.6 estrelas) mas presença digital muito fraca. Oportunidade de longo prazo para estruturar presença online.",
    suggestedMessage: "Oi, Marco! Vi que o Sabor & Arte tem ótimas avaliações no Google — 4.6 estrelas é excelente. Mas percebi que vocês ainda não têm site nem captação digital estruturada. Isso significa que muita gente que pesquisa restaurante italiano em SP pode não estar te encontrando. Posso te mostrar como resolver isso de forma simples?",
    status: "new",
    termsFound: ["reservas", "menu especial"],
    problemsFound: ["Sem site", "Sem e-mail comercial", "Instagram com baixo engajamento"],
    signals: [],
    observations: "",
    createdAt: "2026-05-04T18:00:00Z",
    updatedAt: "2026-05-04T18:00:00Z",
  },
  {
    id: "7",
    campaignId: "c3",
    name: "JurisTech Advogados",
    niche: "Advogados",
    subniche: "Direito Empresarial",
    website: "https://juristech.adv.br",
    instagram: "@juristechadv",
    linkedin: "linkedin.com/company/juristech",
    email: "contato@juristech.adv.br",
    phone: "(11) 4002-8922",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    responsible: "Dr. Felipe Corrêa",
    source: "LinkedIn",
    sourceUrl: "https://linkedin.com/company/juristech",
    score: 78,
    temperature: "hot",
    scoreReason: "Anunciando no Google (+20), tem formulário de captação (+10), página de serviços (+15). Publica sobre 'diagnóstico gratuito' e 'consultoria inicial' (+20). Site lento (+10).",
    opportunity: "Escritório de advocacia empresarial com captação digital ativa. Anunciam mas não têm landing pages segmentadas por serviço. Alta oportunidade para aumentar conversão por especialidade.",
    suggestedMessage: "Oi, Felipe! Vi que o JurisTech está com anúncios rodando — excelente posicionamento digital para um escritório B2B. Identifiquei que vocês estão enviando todo o tráfego para a página inicial, mas landing pages segmentadas por serviço (trabalhista, contratual, etc.) convertem em média 3x mais. Vale uma conversa?",
    status: "new",
    termsFound: ["diagnóstico gratuito", "consultoria inicial", "empresas em crescimento"],
    problemsFound: ["Sem landing pages por serviço", "Site lento", "Sem segmentação de anúncios"],
    signals: [
      { id: "s11", leadId: "7", signalType: "advertising", signalDescription: "Google Ads ativo", points: 20, createdAt: "2026-05-05" },
      { id: "s12", leadId: "7", signalType: "intent_terms", signalDescription: "'Diagnóstico gratuito' e 'consultoria inicial'", points: 20, createdAt: "2026-05-05" },
    ],
    observations: "",
    createdAt: "2026-05-05T07:45:00Z",
    updatedAt: "2026-05-05T07:45:00Z",
  },
  {
    id: "8",
    campaignId: "c2",
    name: "EduTech — Curso Online de Programação",
    niche: "Infoprodutores",
    subniche: "Cursos de Tecnologia",
    website: "https://edutechprogramacao.com.br",
    instagram: "@edutechprog",
    linkedin: "linkedin.com/company/edutech",
    email: "suporte@edutech.com.br",
    phone: "(51) 98765-0000",
    city: "Porto Alegre",
    state: "RS",
    country: "Brasil",
    responsible: "Thiago Ventura",
    source: "Meta Ads Library",
    sourceUrl: "https://facebook.com/ads/library/edutech",
    score: 95,
    temperature: "hot",
    scoreReason: "Lançamento ativo (+20), anúncios Meta (+20), checkout Hotmart (+15), página de vendas (+15), termos 'aula gratuita', 'turma aberta', 'vagas limitadas' (+20). Anúncios com alta frequência mas funil com gap (+15).",
    opportunity: "Infoprodutor em lançamento com alto investimento em ads. Funil tem gap entre a aula gratuita e o checkout — queda de conversão estimada em 40%. Oportunidade clara para sequência de e-mail e WhatsApp automatizada.",
    suggestedMessage: "Oi, Thiago! Acompanhei o lançamento da EduTech — os anúncios da aula gratuita estão com ótima performance. Mas identifiquei que há um gap grande entre quem assiste à aula e quem chega ao checkout. Com uma sequência de follow-up estruturada, você poderia recuperar facilmente 30-40% desse volume. Posso te mostrar o que encontrei?",
    status: "new",
    termsFound: ["aula gratuita", "turma aberta", "vagas limitadas", "método exclusivo"],
    problemsFound: ["Gap no funil entre aula e checkout", "Sem automação de follow-up", "Sem segmentação de remarketing"],
    signals: [
      { id: "s13", leadId: "8", signalType: "launch", signalDescription: "Lançamento com 'turma aberta'", points: 20, createdAt: "2026-05-05" },
      { id: "s14", leadId: "8", signalType: "advertising", signalDescription: "Meta Ads com alta frequência", points: 20, createdAt: "2026-05-05" },
      { id: "s15", leadId: "8", signalType: "checkout", signalDescription: "Checkout Hotmart ativo", points: 15, createdAt: "2026-05-05" },
      { id: "s16", leadId: "8", signalType: "funnel_gap", signalDescription: "Funil incompleto — gap identificado", points: 15, createdAt: "2026-05-05" },
    ],
    observations: "",
    createdAt: "2026-05-05T06:00:00Z",
    updatedAt: "2026-05-05T06:00:00Z",
  },
  {
    id: "9",
    campaignId: "c1",
    name: "Dra. Carla Wellness — Nutrologia",
    niche: "Consultórios",
    subniche: "Nutrologia e Emagrecimento",
    website: "https://dracarlawellness.com.br",
    instagram: "@dracarlawellness",
    linkedin: undefined,
    email: "agenda@dracarlawellness.com.br",
    phone: "(11) 99012-3456",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    responsible: "Dra. Carla Monteiro",
    source: "Instagram",
    sourceUrl: "https://instagram.com/dracarlawellness",
    score: 82,
    temperature: "hot",
    scoreReason: "Anúncios no Meta (+20), agenda aberta publicada (+15), formulário de captação (+10), usa 'consulta online' e 'programa de emagrecimento' (+20), design desatualizado (+10), WhatsApp sem bot de qualificação (+10).",
    opportunity: "Médica nutróloga com anúncios ativos e agenda lotando. Processo de agendamento manual e sem qualificação prévia — perde tempo com consultas inadequadas. Oportunidade de automação e funil de pré-qualificação.",
    suggestedMessage: "Oi, Dra. Carla! Vi que a agenda está aberta e os anúncios estão rodando bem. Mas percebi que o WhatsApp recebe tudo sem filtro — pacientes sem perfil, dúvidas genéricas, e quem realmente quer consultar fica misturado. Com um funil de pré-qualificação simples, você recebe só quem está pronto para marcar. Faz sentido eu mostrar como funciona?",
    status: "new",
    termsFound: ["agenda aberta", "consulta online", "programa de emagrecimento", "resultado em 30 dias"],
    problemsFound: ["WhatsApp sem qualificação", "Design desatualizado", "Processo manual de agendamento"],
    signals: [
      { id: "s17", leadId: "9", signalType: "advertising", signalDescription: "Meta Ads ativos", points: 20, createdAt: "2026-05-05" },
      { id: "s18", leadId: "9", signalType: "agenda", signalDescription: "'Agenda aberta' publicado no Instagram", points: 15, createdAt: "2026-05-05" },
      { id: "s19", leadId: "9", signalType: "intent_terms", signalDescription: "'Consulta online' e 'programa de emagrecimento'", points: 20, createdAt: "2026-05-05" },
    ],
    observations: "",
    createdAt: "2026-05-05T09:00:00Z",
    updatedAt: "2026-05-05T09:00:00Z",
  },
  {
    id: "10",
    campaignId: "c3",
    name: "UrbanSpace Imobiliária",
    niche: "Imobiliárias",
    subniche: "Alto Padrão",
    website: "https://urbanspaceimob.com.br",
    instagram: "@urbanspaceimob",
    linkedin: "linkedin.com/company/urbanspace",
    email: "contato@urbanspace.com.br",
    phone: "(11) 3210-9876",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    responsible: "Carlos Drummond",
    source: "Google Search",
    sourceUrl: "https://google.com/search?q=urbanspace+imoveis",
    score: 71,
    temperature: "hot",
    scoreReason: "Anunciando no Google (+20), tem formulário de captação (+10), usa 'lançamento exclusivo' e 'unidades limitadas' (+20), anuncia mas landing page fraca (+25). Sem pixel de remarketing.",
    opportunity: "Imobiliária de alto padrão investindo em Google Ads para lançamentos, mas sem landing page dedicada por empreendimento. Cada visita ao site geral perde contexto e urgência. Alta oportunidade para landing pages segmentadas.",
    suggestedMessage: "Oi, Carlos! Vi que a UrbanSpace está com campanhas rodando para os lançamentos — ótima estratégia. Só que percebi que o tráfego dos anúncios vai todo para o site geral, sem landing page específica por empreendimento. Isso dilui a conversão. Para imobiliárias de alto padrão, landing pages segmentadas costumam triplicar a taxa de leads qualificados. Posso te mostrar um exemplo?",
    status: "new",
    termsFound: ["lançamento exclusivo", "unidades limitadas", "alto padrão", "financiamento direto"],
    problemsFound: ["Sem landing page por empreendimento", "Sem remarketing", "Pixel não configurado"],
    signals: [
      { id: "s20", leadId: "10", signalType: "advertising", signalDescription: "Google Ads para lançamentos", points: 20, createdAt: "2026-05-04" },
      { id: "s21", leadId: "10", signalType: "intent_terms", signalDescription: "'Lançamento exclusivo' e 'unidades limitadas'", points: 20, createdAt: "2026-05-04" },
      { id: "s22", leadId: "10", signalType: "weak_landing", signalDescription: "Anuncia mas direciona para home geral", points: 25, createdAt: "2026-05-04" },
    ],
    observations: "",
    createdAt: "2026-05-04T13:00:00Z",
    updatedAt: "2026-05-04T13:00:00Z",
  },
  {
    id: "11",
    campaignId: "c2",
    name: "Shape Total Academia",
    niche: "Academias",
    subniche: "Funcional e HIIT",
    website: "https://shapetotal.com.br",
    instagram: "@shapetotalac",
    linkedin: undefined,
    email: "contato@shapetotal.com.br",
    phone: "(21) 99123-4567",
    city: "Rio de Janeiro",
    state: "RJ",
    country: "Brasil",
    responsible: "Bruno Freitas",
    source: "Meta Ads Library",
    sourceUrl: "https://facebook.com/ads/library/shapetotal",
    score: 79,
    temperature: "hot",
    scoreReason: "Anunciando no Meta (+20), usa 'matrícula aberta', 'primeira semana grátis' e 'turmas novas' (+20), tem formulário de captação (+10), WhatsApp sem qualificação (+10), design desatualizado (+10), funil incompleto (+15).",
    opportunity: "Academia com anúncios de captação ativos, mas fluxo pós-clique sem estrutura. Leads entram pelo formulário e caem no WhatsApp sem contexto. Oportunidade de automação do onboarding digital.",
    suggestedMessage: "Oi, Bruno! Vi que a Shape Total está com 'matrícula aberta' e rodando anúncios. Ótima iniciativa. Mas identifiquei que depois do clique no anúncio, o processo de conversão ainda é manual e sem estrutura. Isso faz você perder leads quentes que precisavam só de um empurrãozinho. Posso te mostrar como automatizar esse fluxo?",
    status: "new",
    termsFound: ["matrícula aberta", "primeira semana grátis", "turmas novas", "personal trainer"],
    problemsFound: ["Fluxo pós-clique sem estrutura", "WhatsApp sem contexto", "Funil incompleto"],
    signals: [
      { id: "s23", leadId: "11", signalType: "advertising", signalDescription: "Meta Ads com 'matrícula aberta'", points: 20, createdAt: "2026-05-05" },
      { id: "s24", leadId: "11", signalType: "intent_terms", signalDescription: "'Primeira semana grátis' e 'turmas novas'", points: 20, createdAt: "2026-05-05" },
    ],
    observations: "",
    createdAt: "2026-05-05T08:00:00Z",
    updatedAt: "2026-05-05T08:00:00Z",
  },
  {
    id: "12",
    campaignId: "c1",
    name: "Método Clara — Coach de Vida",
    niche: "Infoprodutores",
    subniche: "Coaching e Desenvolvimento Pessoal",
    website: "https://metodoclara.com.br",
    instagram: "@metodoclara",
    linkedin: "linkedin.com/in/clarasantos",
    email: "ola@metodoclara.com.br",
    phone: "(41) 98888-7777",
    city: "Curitiba",
    state: "PR",
    country: "Brasil",
    responsible: "Clara Santos",
    source: "Instagram",
    sourceUrl: "https://instagram.com/metodoclara",
    score: 73,
    temperature: "hot",
    scoreReason: "Tem página de vendas (+15), usa 'turma nova', 'imersão' e 'transformação' (+20), tem formulário de captura (+10), tem checkout (+15), site (+5), Instagram (+5). Design um pouco datado (+10).",
    opportunity: "Coach com produto estruturado e página de vendas ativa, mas sem tráfego pago. Crescimento atual é orgânico — alto potencial de escala com campanhas Meta bem segmentadas.",
    suggestedMessage: "Oi, Clara! Acompanhei o lançamento da sua imersão e vi que o engajamento orgânico está forte. A pergunta que fica é: quantas pessoas poderiam estar vendo isso se você tivesse tráfego pago? Com o produto que você tem, o potencial de escala é enorme. Posso te mostrar como funcionaria?",
    status: "new",
    termsFound: ["turma nova", "imersão", "transformação", "vagas abertas"],
    problemsFound: ["Sem tráfego pago", "Crescimento apenas orgânico", "Design datado"],
    signals: [
      { id: "s25", leadId: "12", signalType: "sales_page", signalDescription: "Página de vendas com checkout ativo", points: 15, createdAt: "2026-05-03" },
      { id: "s26", leadId: "12", signalType: "intent_terms", signalDescription: "'Turma nova', 'imersão' e 'transformação'", points: 20, createdAt: "2026-05-03" },
      { id: "s27", leadId: "12", signalType: "checkout", signalDescription: "Checkout ativo identificado", points: 15, createdAt: "2026-05-03" },
    ],
    observations: "",
    createdAt: "2026-05-03T15:30:00Z",
    updatedAt: "2026-05-03T15:30:00Z",
  },
  {
    id: "13",
    campaignId: "c2",
    name: "Studio Glow — Micropigmentação",
    niche: "Clínicas de Estética",
    subniche: "Micropigmentação e Design",
    website: "https://studioglow.com.br",
    instagram: "@studioglowoficial",
    linkedin: undefined,
    email: "ola@studioglow.com.br",
    phone: "(19) 98765-1111",
    city: "Campinas",
    state: "SP",
    country: "Brasil",
    responsible: "Letícia Gomes",
    source: "Instagram",
    sourceUrl: "https://instagram.com/studioglowoficial",
    score: 68,
    temperature: "warm",
    scoreReason: "Instagram ativo (+5), site (+5), e-mail (+5), WhatsApp (+5). Usa 'agenda com vagas' (+15), tem formulário (+10), design ok. Sem anúncios identificados. WhatsApp sem automação (+10).",
    opportunity: "Studio com forte presença orgânica e agenda ocupada. Sem anúncios estruturados — cresce por indicação. Momento ideal para escalar com Meta Ads segmentados por cidade e interesse em estética.",
    suggestedMessage: "Oi, Letícia! O Studio Glow tem presença incrível no Instagram — conteúdo de qualidade e muito engajamento. Vi que a agenda está sempre cheia por indicação. A pergunta é: e as pessoas que ainda não te conhecem? Com uma campanha Meta bem feita, você poderia multiplicar o alcance sem depender só de indicação. Faz sentido conversar?",
    status: "new",
    termsFound: ["agenda com vagas", "micropigmentação", "design de sobrancelha"],
    problemsFound: ["Sem anúncios pagos", "WhatsApp sem automação", "Crescimento apenas orgânico"],
    signals: [
      { id: "s28", leadId: "13", signalType: "agenda", signalDescription: "'Agenda com vagas' publicado regularmente", points: 15, createdAt: "2026-05-04" },
      { id: "s29", leadId: "13", signalType: "form", signalDescription: "Formulário de agendamento online", points: 10, createdAt: "2026-05-04" },
    ],
    observations: "",
    createdAt: "2026-05-04T10:00:00Z",
    updatedAt: "2026-05-04T10:00:00Z",
  },
  {
    id: "14",
    campaignId: "c3",
    name: "Borges & Lima Advocacia",
    niche: "Advogados",
    subniche: "Direito Trabalhista",
    website: "https://borgeslimaadv.com.br",
    instagram: "@borgeslimaadv",
    linkedin: "linkedin.com/company/borgeslimaadv",
    email: "contato@borgeslimaadv.com.br",
    phone: "(41) 3344-2211",
    city: "Curitiba",
    state: "PR",
    country: "Brasil",
    responsible: "Dr. Henrique Borges",
    source: "LinkedIn",
    sourceUrl: "https://linkedin.com/company/borgeslimaadv",
    score: 48,
    temperature: "warm",
    scoreReason: "Tem site (+5), Instagram (+5), e-mail (+5), LinkedIn (+5). Publica sobre 'consulta gratuita' (+20). Sem anúncios identificados. Site sem CTA claro (+10).",
    opportunity: "Escritório trabalhista com presença digital básica. Publica conteúdo de autoridade mas sem captação estruturada. Momento de escalar com Google Ads para termos de busca como 'advogado trabalhista Curitiba'.",
    suggestedMessage: "Oi, Dr. Henrique! Vi o conteúdo educativo do Borges & Lima no LinkedIn — excelente posicionamento de autoridade. Mas percebi que não há captação estruturada para quem está buscando ativamente 'advogado trabalhista Curitiba' no Google. Esse tráfego existe e está indo para a concorrência. Vale uma conversa sobre como capturá-lo?",
    status: "new",
    termsFound: ["consulta gratuita", "direitos trabalhistas", "demissão sem justa causa"],
    problemsFound: ["Sem Google Ads", "Site sem CTA claro", "Captação apenas orgânica"],
    signals: [
      { id: "s30", leadId: "14", signalType: "intent_terms", signalDescription: "'Consulta gratuita' publicado no LinkedIn", points: 20, createdAt: "2026-05-02" },
    ],
    observations: "",
    createdAt: "2026-05-02T11:00:00Z",
    updatedAt: "2026-05-02T11:00:00Z",
  },
  {
    id: "15",
    campaignId: "c1",
    name: "Pizzaria Don Carlo",
    niche: "Restaurantes",
    subniche: "Pizzaria Artesanal",
    website: "https://doncarlo.com.br",
    instagram: "@doncarlopizzaria",
    linkedin: undefined,
    email: "pedidos@doncarlo.com.br",
    phone: "(11) 3456-7891",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    responsible: "Carlo Mancini",
    source: "Google Maps",
    sourceUrl: "https://maps.google.com/?cid=doncarlo",
    score: 43,
    temperature: "warm",
    scoreReason: "Tem site (+5), Instagram (+5), e-mail (+5), WhatsApp (+5). Sem anúncios identificados. Publica sobre 'novos sabores' e 'delivery' (+15). Site com design desatualizado (+10).",
    opportunity: "Pizzaria com boa presença local mas sem captação de delivery estruturada. Oportunidade de criar campanhas de geolocalização para atrair moradores do bairro com ofertas específicas.",
    suggestedMessage: "Oi, Carlo! Vi que o Don Carlo tem boa avaliação e Instagram ativo. Mas notei que não há campanhas de geolocalização rodando para atrair clientes do bairro no delivery. Para restaurantes, esse tipo de campanha tem ROI muito rápido. Posso te mostrar como outros restaurantes em SP estão usando isso?",
    status: "new",
    termsFound: ["novos sabores", "delivery", "promoção de terça"],
    problemsFound: ["Sem anúncios de geolocalização", "Site com design desatualizado", "Sem captação de delivery estruturada"],
    signals: [
      { id: "s31", leadId: "15", signalType: "intent_terms", signalDescription: "'Delivery' e 'novos sabores' publicados regularmente", points: 15, createdAt: "2026-05-03" },
    ],
    observations: "",
    createdAt: "2026-05-03T12:00:00Z",
    updatedAt: "2026-05-03T12:00:00Z",
  },
  {
    id: "16",
    campaignId: "c2",
    name: "Clínica Vita Saúde",
    niche: "Clínicas de Estética",
    subniche: "Estética Corporal e Facial",
    website: "https://vitasaude.com.br",
    instagram: "@vitasaudeclinica",
    linkedin: undefined,
    email: "atendimento@vitasaude.com.br",
    phone: "(62) 99321-4567",
    city: "Goiânia",
    state: "GO",
    country: "Brasil",
    responsible: "Dra. Renata Vaz",
    source: "Google Business",
    sourceUrl: "https://g.page/vitasaudeclinica",
    score: 91,
    temperature: "hot",
    scoreReason: "Anunciando no Meta e Google (+40), tem página de vendas (+15), formulário de agendamento (+10), checkout para pacotes (+15), usa 'promoção de inauguração' e 'agenda aberta' (+20). Funil incompleto (+15).",
    opportunity: "Clínica recém-inaugurada com alto investimento em mídia paga. Infraestrutura de anúncios sólida, mas sem automação pós-captura. Cada lead que entra no WhatsApp sem follow-up automático representa perda significativa.",
    suggestedMessage: "Oi, Dra. Renata! Percebi que a Vita Saúde está com campanha de inauguração forte — parabéns pelo posicionamento. Vi que há um volume alto de leads chegando pelos anúncios, mas sem automação de follow-up, muitos esfiam antes de converter. Com uma sequência de WhatsApp automatizada, você poderia fechar muito mais sem aumentar o time. Posso te mostrar como funciona?",
    status: "new",
    termsFound: ["promoção de inauguração", "agenda aberta", "pacote completo", "resultado garantido"],
    problemsFound: ["Sem automação de follow-up", "WhatsApp sobrecarregado", "Funil incompleto"],
    signals: [
      { id: "s32", leadId: "16", signalType: "advertising", signalDescription: "Meta + Google Ads ativos simultaneamente", points: 40, createdAt: "2026-05-05" },
      { id: "s33", leadId: "16", signalType: "sales_page", signalDescription: "Página de vendas com pacotes", points: 15, createdAt: "2026-05-05" },
      { id: "s34", leadId: "16", signalType: "intent_terms", signalDescription: "'Promoção de inauguração' e 'agenda aberta'", points: 20, createdAt: "2026-05-05" },
    ],
    observations: "",
    createdAt: "2026-05-05T07:00:00Z",
    updatedAt: "2026-05-05T07:00:00Z",
  },
];

export const mockCampaigns: SearchCampaign[] = [
  {
    id: "c1",
    userId: "u1",
    name: "Especialistas SP — Lançamentos",
    niche: "Infoprodutores",
    keywords: ["lançamento", "mentoria", "aula gratuita", "lista de espera", "vagas limitadas"],
    location: "São Paulo, SP",
    frequency: "weekly",
    status: "active",
    sources: ["instagram", "meta_ads", "linkedin", "google_search"],
    minScore: 60,
    maxLeads: 50,
    intentSignals: ["advertising", "launch", "checkout", "hiring"],
    leadsFound: 23,
    createdAt: "2026-04-20T10:00:00Z",
    lastRunAt: "2026-05-05T06:00:00Z",
  },
  {
    id: "c2",
    userId: "u1",
    name: "Saúde & Bem-estar — BH e SP",
    niche: "Clínicas de Estética",
    keywords: ["agenda aberta", "harmonização", "procedimento estético", "emagrecimento"],
    location: "Belo Horizonte, MG | São Paulo, SP",
    frequency: "daily",
    status: "active",
    sources: ["google_maps", "instagram", "google_business"],
    minScore: 50,
    maxLeads: 100,
    intentSignals: ["advertising", "sales_page", "form_capture"],
    leadsFound: 41,
    createdAt: "2026-04-25T14:00:00Z",
    lastRunAt: "2026-05-05T08:00:00Z",
  },
  {
    id: "c3",
    userId: "u1",
    name: "Escritórios e Imobiliárias — Sul",
    niche: "Advogados",
    keywords: ["diagnóstico gratuito", "consultoria", "empresas em crescimento"],
    location: "Sul do Brasil",
    frequency: "weekly",
    status: "active",
    sources: ["linkedin", "google_search", "google_business"],
    minScore: 55,
    maxLeads: 30,
    intentSignals: ["advertising", "hiring", "intent_terms"],
    leadsFound: 12,
    createdAt: "2026-04-28T09:00:00Z",
    lastRunAt: "2026-05-04T22:00:00Z",
  },
];

export const mockNiches: NicheSummary[] = [
  {
    niche: "Infoprodutores",
    totalLeads: 18,
    avgScore: 80,
    hotLeads: 14,
    warmLeads: 3,
    coldLeads: 1,
    topSignals: ["Lançamento ativo", "Anúncios Meta", "Lista de espera", "Checkout ativo"],
    topPains: ["Funil incompleto", "Sem automação de follow-up", "Gap entre captura e venda"],
    bestApproach: "Abordar durante a fase de lançamento destacando oportunidade de recuperar leads que não converteram e automatizar follow-up.",
  },
  {
    niche: "Clínicas de Estética",
    totalLeads: 14,
    avgScore: 82,
    hotLeads: 11,
    warmLeads: 2,
    coldLeads: 1,
    topSignals: ["Instagram Ads ativo", "Agenda aberta", "Formulário de agendamento"],
    topPains: ["Landing page fraca", "WhatsApp sem qualificação", "Funil de agendamento confuso"],
    bestApproach: "Focar em conversão — mostrar como otimizar o caminho do anúncio até o agendamento confirmado.",
  },
  {
    niche: "Advogados",
    totalLeads: 9,
    avgScore: 63,
    hotLeads: 5,
    warmLeads: 4,
    coldLeads: 0,
    topSignals: ["Google Ads ativo", "Diagnóstico gratuito", "Publicações de autoridade"],
    topPains: ["Sem landing pages por serviço", "Tráfego para home page", "Sem segmentação"],
    bestApproach: "Mostrar como segmentar campanhas por especialidade aumenta a conversão e reduz custo por lead qualificado.",
  },
  {
    niche: "Academias",
    totalLeads: 8,
    avgScore: 70,
    hotLeads: 4,
    warmLeads: 3,
    coldLeads: 1,
    topSignals: ["Meta Ads com matrículas", "Contratando equipe de marketing", "Turmas novas"],
    topPains: ["Fluxo pós-clique sem estrutura", "Site desatualizado", "WhatsApp sem automação"],
    bestApproach: "Abordar no momento da contratação da equipe — oferecer estrutura enquanto o time interno é montado.",
  },
  {
    niche: "Consultórios",
    totalLeads: 11,
    avgScore: 78,
    hotLeads: 8,
    warmLeads: 2,
    coldLeads: 1,
    topSignals: ["Agenda aberta", "Google Ads ativo", "Formulário de agendamento"],
    topPains: ["WhatsApp sem qualificação", "Processo manual de agendamento", "Pixel não configurado"],
    bestApproach: "Vender automação do processo de agendamento — mostrar como pré-qualificar pacientes antes do WhatsApp chegar na agenda.",
  },
  {
    niche: "Imobiliárias",
    totalLeads: 7,
    avgScore: 62,
    hotLeads: 3,
    warmLeads: 3,
    coldLeads: 1,
    topSignals: ["Google Ads para lançamentos", "Lançamento exclusivo", "Contratando corretores"],
    topPains: ["Sem landing page por empreendimento", "Sem remarketing", "Captação apenas orgânica"],
    bestApproach: "Propor landing pages por empreendimento com formulário de interesse — aumenta qualidade e quantidade de leads por lançamento.",
  },
  {
    niche: "Restaurantes",
    totalLeads: 5,
    avgScore: 35,
    hotLeads: 0,
    warmLeads: 2,
    coldLeads: 3,
    topSignals: ["Delivery ativo", "Instagram com conteúdo regular", "Promoções sazonais"],
    topPains: ["Sem site ou site desatualizado", "Sem captação de delivery estruturada", "Presença digital fraca"],
    bestApproach: "Mostrar oportunidade de geolocalização — como capturar clientes que buscam restaurantes próximos e ainda não conhecem a marca.",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalLeads: 87,
  hotLeads: 38,
  warmLeads: 31,
  coldLeads: 18,
  topNiche: "Infoprodutores",
  avgScore: 69,
  lastSearchAt: "2026-05-05T08:00:00Z",
  newLeadsToday: 8,
  newLeadsWeek: 34,
};
